disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - type_body_length
  - file_length
  - cyclomatic_complexity

opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_imports
  - static_operator
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition
  - prefer_self_in_static_references
  - prefer_zero_over_explicit_init
  - redundant_string_enum_value
  - redundant_type_annotation
  - sorted_first_last
  - unused_import
  - vertical_parameter_alignment_on_call

included:
  - Notes
  - NotesTests
  - NotesUITests

excluded:
  - DerivedData
  - .build
  - Pods

line_length:
  warning: 120
  error: 150

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 10
  error: 20

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50

nesting:
  type_level:
    warning: 3
    error: 5
  statement_level:
    warning: 5
    error: 10

# Additional style rules
prefer_self_in_static_references: true
prefer_zero_over_explicit_init: true
redundant_string_enum_value: true
sorted_first_last: true
unused_import: true



